/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h94b317f4efd213ea: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__he14aa0271108db36: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h51e9c53b1d9a35ee: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h100319400c037366: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h21765a12b403fcc5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h2947530277d59059: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h9598766e4fa39a6e: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
