[package]
name = "markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-iterator = "2.1.0"
gray_matter = "0.2.6"
macros = { path = "../macros" }
postcard = { version = "1.0.8", features = ["use-std"] }
pulldown-cmark = "0.11.0"
serde = "1.0.200"
