[package]
name = "markdown"
version = "0.7.2"
edition = "2021"

[dependencies]
chrono = { workspace = true }
enum-iterator = "2.1.0"
gray_matter = "0.2.6"
macros = { path = "../macros" }
pulldown-cmark = "0.11.0"
ron = { workspace = true }
serde = { workspace = true }
serde_with = { version = "3.22.0", default-features = false, features = ["chrono_0_4"] }
syntect = { version = "5.2.0", default-features = false, features = ["default-fancy"] }
