/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const MobileHeader_4700568660252565466: (a: any) => void;
export const hydrate: () => void;
export const PostDisplay_4753120722354914321: (a: any) => void;
export const Background_7011291641563722467: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen__closure__destroy__h5fb2d701bac1d285: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h13e621c27c70b0f3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hf78b2869b6ce0214: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb5a2e7f49e30c8ba: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h13450b5bd568a836: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hf8d4ba5c88931097: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha4b55bc69ed1ebc6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0d2810dbdf663016: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
