/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__ha8e5e41b2d52a77d: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h4ffc17f50f363357: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hed78ce3951be6750: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h544a5e08b3d059e1: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h32724aaa35d55028: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h04542028275cc3b6: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h60e9f0752214a7fb: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
