[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.81"
quote = "1.0.36"
serde = { version = "1.0.209", features = ["derive"] }
serde_yml = "0.0.12"
syn = "2.0.60"
