/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const PostDisplay_9641767229574460062: (a: any) => void;
export const hydrate: () => void;
export const Background_7011291641563722467: (a: any) => void;
export const CommentToggle_7761011648576428996: (a: any) => void;
export const MobileHeader_4700568660252565466: (a: any) => void;
export const OAuth_12876817204350332409: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke___wasm_bindgen_f26c518886d2618f___JsValue__core_ed718c3d60ebd546___result__Result_____wasm_bindgen_f26c518886d2618f___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke___js_sys_51bef2bf132a57dd___Array__web_sys_e560035b4bc8eabf___features__gen_ResizeObserver__ResizeObserver______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke___js_sys_51bef2bf132a57dd___Function_fn_wasm_bindgen_f26c518886d2618f___JsValue_____wasm_bindgen_f26c518886d2618f___sys__Undefined___js_sys_51bef2bf132a57dd___Function_fn_wasm_bindgen_f26c518886d2618f___JsValue_____wasm_bindgen_f26c518886d2618f___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke___wasm_bindgen_f26c518886d2618f___JsValue______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke___wasm_bindgen_f26c518886d2618f___JsValue______true__3: (a: number, b: number, c: any) => void;
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const wasm_bindgen_f26c518886d2618f___convert__closures_____invoke_______true__1_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
