/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const Background_7011291641563722467: (a: any) => void;
export const CommentToggle_7761011648576428996: (a: any) => void;
export const OAuth_12876817204350332409: (a: any) => void;
export const hydrate: () => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const MobileHeader_4700568660252565466: (a: any) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen__closure__destroy__h732871e95e821f37: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__ha745a129110b87b3: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hb9d5e5823876248f: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h69136c77ad10c91c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h889e4da64d1bb9b7: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1fe821fd2ad1cf18: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hfe4e80d97b6e1b75: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h12ef2d32b050317e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h514b433feefd896e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc8a87f8c5157ddb2: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
