/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const CommentToggle_7761011648576428996: (a: any) => void;
export const OAuth_12876817204350332409: (a: any) => void;
export const MobileHeader_4700568660252565466: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const Background_7011291641563722467: (a: any) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const wasm_bindgen__closure__destroy__hc7ecdcae91023a5a: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hf48e58f034c673c0: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h21313cd6a9307c96: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h932bdcfdbe694c5a: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hbd8275dca5491cbd: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0cdb8634e78189d1: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__had989ec96762a74c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hf55f8353cb50513c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h2ebd2e29913d7697: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb541decc0a191130: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
