/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const Background_7011291641563722467: (a: any) => void;
export const MobileHeader_4700568660252565466: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen__closure__destroy__h07ca71633275e889: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h7c8d390a6aa30947: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h916191ee89e07876: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h0dbac7b2852a16ba: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h894ddb53314a400d: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd2830fb6619f2ecf: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hcc16ef845e62f5ff: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1d6196c2af6dfc13: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
