/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const Background_7011291641563722467: (a: any) => void;
export const MobileHeader_4700568660252565466: (a: any) => void;
export const hydrate: () => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const wasm_bindgen__closure__destroy__h3f505c6fe971536b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hcfc9155197a1cfb2: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h2222fd2ed539da07: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5807de9b6a5b46e9: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__haac33146aeca4ba5: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9f57b41fed8437b7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hb6b8c822685733d2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4840390a50b377cc: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
