/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const Background_7011291641563722467: (a: any) => void;
export const MobileHeader_14484353534515111953: (a: any) => void;
export const hydrate: () => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const wasm_bindgen__closure__destroy__h147f6485a17efb39: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h8216cadf55ebc7b9: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__he2fcbb4cd5a130f8: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h8d63a1e6aa0eef59: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h453eb45db7fcf7ce: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hdcb0ca9e91738b6a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h71ed9389187f7747: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h5181d99eca6ff10e: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
