name: Deploy static website to GH Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # ==================== SETUP ====================
      # Install Rust
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      # Install Trunk and WASM for building webapp
      - uses: jetli/trunk-action@v0.5.0
      - uses: jetli/wasm-bindgen-action@v0.2.0
        with:
          version: '0.2.92'
      # Install Node and PNPM
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      # Checkout repo
      - uses: actions/checkout@v4
      # =================== INSTALL ===================
      # Cache Rust build files
      - uses: Swatinem/rust-cache@v2
      # PNPM caching and installing dependencies
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-server-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      # ==================== BUILD ====================
      - name: Build website
        run: pnpm build
      # =================== DEPLOY ====================
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
