/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const Background_7011291641563722467: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const MobileHeader_16574637277494047394: (a: any) => void;
export const hydrate: () => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen__closure__destroy__h3c29dc6a19bc6a94: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h69136c77ad10c91c: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h152f8ec9be45b2e4: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc0856cbea3035068: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1fe821fd2ad1cf18: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd625f1318171ca0f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h12ef2d32b050317e: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h7c8b7aeff3e9c391: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
