/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const hydrate: () => void;
export const Background_7011291641563722467: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const MobileHeader_5252500168264856710: (a: any) => void;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const wasm_bindgen__convert__closures_____invoke__h859dc728cfa0e49b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h15cd4d84ae30497b: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h78ed79784ecf0eba: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__closure__destroy__h3ec76fd1df8baf58: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h058336d904c225b1: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h8a80103bdb67f4f9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h7fe0a5fedd888bce: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h051ea63d98b6ed6d: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
