/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const MobileHeader_5252500168264856710: (a: any) => void;
export const Background_7011291641563722467: (a: any) => void;
export const HomeAnimation_14651908795469971363: (a: any) => void;
export const hydrate: () => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const intounderlyingsink_abort: (a: number, b: any) => any;
export const intounderlyingsink_close: (a: number) => any;
export const intounderlyingsink_write: (a: number, b: any) => any;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: any) => any;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: any) => any;
export const intounderlyingbytesource_start: (a: number, b: any) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const wasm_bindgen__closure__destroy__h8273e96594845640: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h932bdcfdbe694c5a: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__hfd1b4a730d2c391c: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2c1ee4464a116c54: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0cdb8634e78189d1: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h00bbe00d7b18ec3f: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hf55f8353cb50513c: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h15c374e81f2b513f: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
